services:
  backend:
    image: ${YOUR_REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/backend:${TAG}
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ENV=development
      - GOOGLE_APPLICATION_CREDENTIALS=/app/backend/config/insightsmix-cda5c2afe3e7.json
      - PYTHONUNBUFFERED=1
    volumes:
      - ./logs:/app/logs
      - ./backend:/app/backend
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    networks:
      - app-network
    depends_on:
      - vertez

  frontend:
    image: ${YOUR_REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/frontend:${TAG}
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./logs:/app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    environment:
      - REACT_APP_API_URL=http://backend:8080
    depends_on:
      - backend
    networks:
      - app-network

  vertez:
    image: ${YOUR_REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/vertez:${TAG}
    build:
      context: ./vertez
      dockerfile: Dockerfile
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - ./logs:/app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"

networks:
  app-network:
    driver: bridge